# Generated by Django 5.2.1 on 2025-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0002_user_bio_user_location_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(related_name='users_with_skill', to='skills.skill'),
        ),
    ]
