# Generated by Django 5.2.1 on 2025-06-06 12:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_charity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='django_test/'),
        ),
    ]
