# Generated by Django 5.2.1 on 2025-06-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='charity_id',
            new_name='charity',
        ),
    ]
