# Generated by Django 5.2.1 on 2025-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_rename_charity_id_opportunity_charity'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='skills_required',
            field=models.ManyToManyField(related_name='opportunities', to='skills.skill'),
        ),
    ]
